### ISSUE TITLE
Cannot Install Dependencies for app.js

### ISSUE THREAD

**Issue by ghost** [CSCI-4830-002-2014/challenge-week-11#2]
When I try to run an npm install to install the dependencies for app.js, it says that the name in package.json "D3+MongoDB+Yelp+Map" is invalid. Here is what my terminal spits out when I try to run an npm install:

![image](https://cloud.githubusercontent.com/assets/8551620/4944096/695eb226-65fa-11e4-9647-da96cf3416c2.png)

**Comment by doubleshow** [comment]
can you try renaming it to something else? like getting rid of the '+' and see if it works again.

**Comment by ghost** [comment]
I got rid of all the plus signs and that fixed it. Thanks!
